name: netconf-client
base: core20 
version: 'git'
summary: Netconf CLI utility to query server
description: |
  The Network Configuration Protocol (NETCONF) is a network management protocol
  developed and standardized by the IETF. 

  More information about the tool is available in the following link.
  https://netconf.readthedocs.io/en/master/index.html

grade: stable
confinement: strict



plugs:
  config-netconf-client:
    interface: system-files
    read:
    - /etc/host.conf


apps:
  netconf-client:
    command: bin/netconf-client
    plugs:
    - network
    - config-netconf-client



parts:
  netconf-client:
    plugin: python
    # python-version: python3
    source-type: git 
    source: https://github.com/choppsv1/netconf
    python-packages:
      - backports.socketpair>=3.5.0.2
      - lxml>=3.1.0
      - monotonic>=1.3
      - paramiko>=1.10.1
      - sshutil>=1.5.0
